### PR TITLE
Replace plain TeX primitives with `\iow_*` l3file functions

### LINKED ISSUE #1: Replace plain TeX primitives with `\iow_*` l3file functions
The `\iow_*` expl3 functions fail in ConTeXt MkII, see https://github.com/latex3/latex3/issues/1103 and https://github.com/latex3/latex3/pull/1114. Since lt3luabridge aims to support ConTeXt MkII, we hotfixed these issues with (plain) TeX commands: https://github.com/Witiko/markdown/pull/141/commits/09f4b2479f2aed20b9e5d982937b454da6a8b32c. After the issues have been closed, we should revert https://github.com/Witiko/markdown/pull/141/commits/09f4b2479f2aed20b9e5d982937b454da6a8b32c and apply a proper fix.

### PR DESCRIPTION
**Pull request by Witiko**
Closes #1.

### CODE REVIEW

**Comment by Witiko** [comment]
Replacing the (plain) TeX primitives with `\iow_*` expl3 functions is blocked by https://github.com/latex3/latex3/issues/1105.

**Comment by Witiko** [comment]
Dear @josephwright, can you please advise why aa1757e would cause the CI to fail? My reading of the l3file documentation is that `\iow_open:Nn`, `\iow_now:Nn`, and `\iow_close:N` should have the same semantics as the `\immediate` variants of `\openout`, `\write`, and `\closeout`. Yet, replacing the latter with the former leads to failure. I am unsure if this is a bug in l3file or my misapprehension of its semantics.

**Comment by josephwright** [comment]
Did you allocate first? We use a pool of streams, so you need `\iow_new:N` before you can open.

**Comment by Witiko** [comment]
I used `\g_tmpa_iow` and thought it was always allocated.

**Comment by Witiko** [comment]
@josephwright I tried to zero in on the cause with the following results:

1. After excluding ConTeXt tests and replacing the `\immediate` variants of `\openout`, `\write`, and `\closeout` with the `\iow_open:Nn`, `\iow_now:Nn`, and `\iow_close:N` functions from expl3-generic in f38c3c9 and b0c8939, all tests pass.
2. After including the ConTeXt MkIV test in bb08ef0, all tests still pass.
3. After including the ConTeXt MkII test in e694f3c, [the MkII test fails][1].

This leads me to the conclusion that there might be an issue with using l3file from expl3-generic in the ConTeXt MkII format that needs to be fixed. I will try to come up with an MWE after I have returned from the vacation next week; if you'd like to look into this in the meantime, it would be appreciated.

 [1]: https://github.com/Witiko/lt3luabridge/runs/7323760574?check_suite_focus=true

**Comment by josephwright** [comment]
Testing on ConTeXt is minimal, and MkII is now two versions 'obsolete' (and hard to set up, as it needs Ruby): I very much doubt there are many real users.

**Comment by Witiko** [comment]
@josephwright That may well be, but I won't break compatibilty without a reason. MkII may be old but it is a superset of plain and usually well-behaved. Would you be interested in a patch to expl3 if I can discover the cause?

**Comment by Witiko** [comment]
@josephwright Mystery solved: It seems that in ConTeXt MkII, `\__iow_new:N` needs to be patched similarly to how you already patch `\__ior_new:N` for ConTeXt MkIV. See https://github.com/Witiko/lt3luabridge/pull/3/commits/bc1d9cc4001b3a6d5ecc8fee869ccaaa33a9e01f.

**Comment by Witiko** [comment]
For my future reference: If https://github.com/latex3/latex3/pull/1114 gets merged, we revert https://github.com/Witiko/lt3luabridge/pull/3/commits/110c8d45a4872ba5eedbb0d9bf63b13f0c141a64 and https://github.com/Witiko/lt3luabridge/pull/3/commits/bc1d9cc4001b3a6d5ecc8fee869ccaaa33a9e01f, and squash before merging https://github.com/Witiko/lt3luabridge/pull/3. Otherwise we revert only https://github.com/Witiko/lt3luabridge/pull/3/commits/110c8d45a4872ba5eedbb0d9bf63b13f0c141a64, document https://github.com/Witiko/lt3luabridge/pull/3/commits/bc1d9cc4001b3a6d5ecc8fee869ccaaa33a9e01f, and squash main..https://github.com/Witiko/lt3luabridge/pull/3/commits/e694f3cc241745e3444a23e62eb0ad7d0a625898 before merging https://github.com/Witiko/lt3luabridge/pull/3.

**Comment by Witiko** [comment]
Try again on Saturday. If successful, revert 82cb941 and merge the PR.

**Pull request merged**
